version: '3.9'

services:

  web:
    container_name: cmalu_urli_web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 42069:8080
    depends_on:
      - database
    links:
      - database
    environment:
      - DB_PORT=3306
      - DB_HOST=database
    env_file:
      - .env

  database:
    image: mariadb:latest
    env_file:
      - .env
    volumes:
      - cmalu_urli_vol:/var/lib/mysql
      - ./dump:/docker-entrypoint-initdb.d

volumes:
  cmalu_urli_vol:
